<?php

namespace App\Http\Controllers\Api\Admin;

use App\Http\Controllers\Controller;
use App\Http\Requests\Admin\ItemRequest;
use App\Http\Resources\Admin\ItemResource;
use App\Models\Item;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Http\JsonResponse;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Symfony\Component\HttpFoundation\StreamedResponse;

class ItemController extends Controller
{
    /**
     * Fields that the frontend is allowed to use for sorting.
     */
    private const SORTABLE_COLUMNS = [
        'id',
        'item_no',
        'item_description',
        'category',
        'unit',
        'status',
        'product_date',
        'type',
        'inventory',
        'registered_by',
        'date_registered',
        'created_at',
        'updated_at',
        'deleted_at',
    ];

    /**
     * Display active and inactive items.
     */
    public function index(Request $request): JsonResponse
    {
        $validated = $request->validate([
            'search' => [
                'nullable',
                'string',
                'max:200',
            ],

            'status' => [
                'nullable',
                'in:active,inactive',
            ],

            'category' => [
                'nullable',
                'string',
                'max:50',
            ],

            'unit' => [
                'nullable',
                'string',
                'max:20',
            ],

            'type' => [
                'nullable',
                'string',
                'max:30',
            ],

            'inventory' => [
                'nullable',
                'string',
                'max:20',
            ],

            'sort_by' => [
                'nullable',
                'string',
            ],

            /*
             * CrudPage currently sends sort_order.
             * BankController uses sort_direction.
             *
             * We accept both so the module remains compatible
             * with either API convention.
             */
            'sort_order' => [
                'nullable',
                'in:asc,desc',
            ],

            'sort_direction' => [
                'nullable',
                'in:asc,desc',
            ],

            'page' => [
                'nullable',
                'integer',
                'min:1',
            ],

            'per_page' => [
                'nullable',
                'integer',
                'min:1',
                'max:100',
            ],
        ]);

        $sortBy = $this->resolveSortColumn(
            $validated['sort_by'] ?? null
        );

        $sortOrder =
            $validated['sort_order']
            ?? $validated['sort_direction']
            ?? 'desc';

        $items = $this->buildFilteredQuery($validated)
            ->orderBy($sortBy, $sortOrder)
            ->paginate(
                $validated['per_page'] ?? 10
            );

        return $this->paginatedResponse(
            $items,
            'Items loaded successfully.'
        );
    }

    /**
     * Store a newly created item.
     */
    public function store(
        ItemRequest $request
    ): JsonResponse {
        $item = DB::transaction(
            function () use ($request): Item {
                /*
                 * PostgreSQL transaction-level advisory lock.
                 *
                 * This prevents two simultaneous requests from
                 * generating the same item number.
                 */
                DB::statement(
                    'SELECT pg_advisory_xact_lock(1002001)'
                );

                $data = $request->validated();

                /*
                 * The item number is generated by the backend.
                 * Any item_no sent by the frontend is ignored.
                 */
                unset($data['item_no']);

                $data['item_no'] =
                    $this->generateNextItemNumber();

                $data = $this->prepareItemData(
                    $data,
                    true
                );

                return Item::create($data);
            }
        );

        return response()->json([
            'success' => true,
            'message' => 'Item created successfully.',
            'data' => new ItemResource(
                $item->fresh()->load('unitOfMeasurement')
            ),
        ], 201);
    }

    /**
     * Display one item.
     */
    public function show(Item $item): JsonResponse
    {
        return response()->json([
            'success' => true,
            'message' => 'Item loaded successfully.',
            'data' => new ItemResource($item),
        ]);
    }

    /**
     * Update an existing item.
     */
    public function update(
        ItemRequest $request,
        Item $item
    ): JsonResponse {
        $data = $request->validated();

        /*
         * Item number is generated once and must not change
         * during normal editing.
         */
        unset(
            $data['item_no'],
            $data['registered_by'],
            $data['registered_by_user_id'],
            $data['date_registered']
        );

        $data = $this->prepareItemData(
            $data,
            false
        );

        $item->update($data);

        return response()->json([
            'success' => true,
            'message' => 'Item updated successfully.',
            'data' => new ItemResource(
                $item->fresh()->load('unitOfMeasurement')
            ),
        ]);
    }

    /**
     * Soft-delete an item.
     */
    public function destroy(Item $item): JsonResponse
    {
        $item->delete();

        return response()->json([
            'success' => true,
            'message' => 'Item moved to the recycle bin.',
        ]);
    }

    /**
     * Display deleted items.
     */
    public function deleted(
        Request $request
    ): JsonResponse {
        $validated = $request->validate([
            'search' => [
                'nullable',
                'string',
                'max:200',
            ],

            'page' => [
                'nullable',
                'integer',
                'min:1',
            ],

            'per_page' => [
                'nullable',
                'integer',
                'min:1',
                'max:100',
            ],
        ]);

        $items = Item::onlyTrashed()
            ->search(
                $validated['search'] ?? null
            )
            ->orderByDesc('deleted_at')
            ->paginate(
                $validated['per_page'] ?? 10
            );

        return $this->paginatedResponse(
            $items,
            'Deleted items loaded successfully.'
        );
    }

    /**
     * Restore a soft-deleted item.
     */
    public function restore(int $id): JsonResponse
    {
        $item = Item::onlyTrashed()
            ->findOrFail($id);

        $item->restore();

        return response()->json([
            'success' => true,
            'message' => 'Item restored successfully.',
            'data' => new ItemResource(
                $item->fresh()->load('unitOfMeasurement')
            ),
        ]);
    }

    /**
     * Permanently delete an item.
     */
    public function forceDelete(
        int $id
    ): JsonResponse {
        $item = Item::onlyTrashed()
            ->findOrFail($id);

        $item->forceDelete();

        return response()->json([
            'success' => true,
            'message' =>
                'Item permanently deleted.',
        ]);
    }

    /**
     * Change active/inactive status.
     */
    public function changeStatus(
        Request $request,
        Item $item
    ): JsonResponse {
        $validated = $request->validate([
            'status' => [
                'required',
                'in:active,inactive',
            ],
        ]);

        $item->update([
            'status' => $validated['status'],
        ]);

        return response()->json([
            'success' => true,
            'message' =>
                'Item status updated successfully.',
            'data' => new ItemResource(
                $item->fresh()->load('unitOfMeasurement')
            ),
        ]);
    }

    /**
     * Return summary cards for CrudPage.
     */
    public function statistics(): JsonResponse
    {
        $statistics = Item::query()
            ->selectRaw('COUNT(*) AS total')
            ->selectRaw(
                "COUNT(*) FILTER (
                    WHERE status = 'active'
                ) AS active"
            )
            ->selectRaw(
                "COUNT(*) FILTER (
                    WHERE status = 'inactive'
                ) AS inactive"
            )
            ->first();

        $deleted = Item::onlyTrashed()->count();

        return response()->json([
            'success' => true,

            /*
             * Return fields directly inside data so that the
             * generic CrudPage statistics API can consume them.
             */
            'data' => [
                'total' => (int) (
                    $statistics?->total ?? 0
                ),

                'active' => (int) (
                    $statistics?->active ?? 0
                ),

                'inactive' => (int) (
                    $statistics?->inactive ?? 0
                ),

                'deleted' => $deleted,
            ],
        ]);
    }

    /**
     * Return distinct field values for filters/forms.
     */
    public function options(): JsonResponse
    {
        return response()->json([
            'success' => true,
            'data' => [
                'categories' => Item::withTrashed()
                    ->whereNotNull('category')
                    ->where('category', '<>', '')
                    ->distinct()
                    ->orderBy('category')
                    ->pluck('category')
                    ->values(),

                'units' => Item::withTrashed()
                    ->whereNotNull('unit')
                    ->where('unit', '<>', '')
                    ->distinct()
                    ->orderBy('unit')
                    ->pluck('unit')
                    ->values(),

                'types' => Item::withTrashed()
                    ->whereNotNull('type')
                    ->where('type', '<>', '')
                    ->distinct()
                    ->orderBy('type')
                    ->pluck('type')
                    ->values(),

                'inventories' => Item::withTrashed()
                    ->whereNotNull('inventory')
                    ->where('inventory', '<>', '')
                    ->distinct()
                    ->orderBy('inventory')
                    ->pluck('inventory')
                    ->values(),
            ],
        ]);
    }

    /**
     * Export filtered items as an Excel-compatible CSV file.
     */
    public function export(
        Request $request
    ): StreamedResponse {
        $validated = $request->validate([
            'search' => [
                'nullable',
                'string',
                'max:200',
            ],

            'status' => [
                'nullable',
                'in:active,inactive',
            ],

            'category' => [
                'nullable',
                'string',
                'max:50',
            ],

            'unit' => [
                'nullable',
                'string',
                'max:20',
            ],

            'type' => [
                'nullable',
                'string',
                'max:30',
            ],

            'inventory' => [
                'nullable',
                'string',
                'max:20',
            ],

            'sort_by' => [
                'nullable',
                'string',
            ],

            'sort_order' => [
                'nullable',
                'in:asc,desc',
            ],

            'sort_direction' => [
                'nullable',
                'in:asc,desc',
            ],
        ]);

        $sortBy = $this->resolveSortColumn(
            $validated['sort_by'] ?? null
        );

        $sortOrder =
            $validated['sort_order']
            ?? $validated['sort_direction']
            ?? 'asc';

        $fileName =
            'items_'
            . now()->format('Y-m-d_H-i-s')
            . '.csv';

        return response()->streamDownload(
            function () use (
                $validated,
                $sortBy,
                $sortOrder
            ): void {
                $handle = fopen(
                    'php://output',
                    'wb'
                );

                if ($handle === false) {
                    return;
                }

                /*
                 * UTF-8 BOM allows Microsoft Excel to display
                 * special characters correctly.
                 */
                fwrite(
                    $handle,
                    "\xEF\xBB\xBF"
                );

                fputcsv($handle, [
                    'ID',
                    'Item Number',
                    'Item Description',
                    'Category',
                    'Unit',
                    'Status',
                    'Product Date',
                    'Type',
                    'Inventory',
                    'Registered By',
                    'Date Registered',
                    'Created At',
                    'Updated At',
                ]);

                $this->buildFilteredQuery($validated)
                    ->orderBy(
                        $sortBy,
                        $sortOrder
                    )
                    ->chunkById(
                        500,
                        function ($items) use (
                            $handle
                        ): void {
                            foreach ($items as $item) {
                                fputcsv($handle, [
                                    $item->id,
                                    $item->item_no,
                                    $item->item_description,
                                    $item->category,
                                    $item->unit,
                                    $item->status,
                                    $item->product_date
                                        ?->format('Y-m-d'),
                                    $item->type,
                                    $item->inventory,
                                    $item->registered_by,
                                    $item->date_registered
                                        ?->format('Y-m-d'),
                                    $item->created_at
                                        ?->format(
                                            'Y-m-d H:i:s'
                                        ),
                                    $item->updated_at
                                        ?->format(
                                            'Y-m-d H:i:s'
                                        ),
                                ]);
                            }
                        }
                    );

                fclose($handle);
            },
            $fileName,
            [
                'Content-Type' =>
                    'text/csv; charset=UTF-8',
            ]
        );
    }

    /**
     * Build the main filtered query.
     */
    private function buildFilteredQuery(
        array $filters
    ): Builder {
        return Item::query()
    ->with('unitOfMeasurement')
            ->search(
                $filters['search'] ?? null
            )
            ->when(
                $filters['status'] ?? null,
                fn (
                    Builder $query,
                    string $status
                ): Builder => $query->where(
                    'status',
                    $status
                )
            )
            ->when(
                $filters['category'] ?? null,
                fn (
                    Builder $query,
                    string $category
                ): Builder => $query->where(
                    'category',
                    $category
                )
            )
            ->when(
                $filters['unit'] ?? null,
                fn (
                    Builder $query,
                    string $unit
                ): Builder => $query->where(
                    'unit',
                    $unit
                )
            )
            ->when(
                $filters['type'] ?? null,
                fn (
                    Builder $query,
                    string $type
                ): Builder => $query->where(
                    'type',
                    $type
                )
            )
            ->when(
                $filters['inventory'] ?? null,
                fn (
                    Builder $query,
                    string $inventory
                ): Builder => $query->where(
                    'inventory',
                    $inventory
                )
            );
    }

    /**
     * Generate ITM1001, ITM1002, ITM1003...
     */
    private function generateNextItemNumber(): string
    {
        $lastNumber = Item::withTrashed()
            ->where(
                'item_no',
                'like',
                'ITM%'
            )
            ->whereRaw(
                "SUBSTRING(item_no FROM 4) ~ '^[0-9]+$'"
            )
            ->selectRaw(
                'MAX(
                    CAST(
                        SUBSTRING(item_no FROM 4)
                        AS INTEGER
                    )
                ) AS max_number'
            )
            ->value('max_number');

        $nextNumber = max(
            (int) $lastNumber + 1,
            1001
        );

        return 'ITM' . $nextNumber;
    }

    /**
     * Add system-managed values.
     */
    private function prepareItemData(
        array $data,
        bool $creating
    ): array {
        if ($creating) {
            $user = request()->user();

            $data['registered_by_user_id'] =
                $user?->id;

            $data['registered_by'] =
                $user?->name
                ?? $user?->email
                ?? 'System';

            $data['date_registered'] =
                $data['date_registered']
                ?? now()->toDateString();
        }

        $data['status'] =
            strtolower(
                trim(
                    (string) (
                        $data['status']
                        ?? 'active'
                    )
                )
            );

        $data['item_description'] =
            trim(
                (string) (
                    $data['item_description']
                    ?? ''
                )
            );

        $data['category'] =
            trim(
                (string) (
                    $data['category']
                    ?? ''
                )
            );

        $data['unit'] =
            trim(
                (string) (
                    $data['unit']
                    ?? ''
                )
            );

        $data['type'] =
            trim(
                (string) (
                    $data['type']
                    ?? ''
                )
            );

        $data['inventory'] =
            trim(
                (string) (
                    $data['inventory']
                    ?? ''
                )
            );

        return $data;
    }

    /**
     * Prevent arbitrary database-column sorting.
     */
    private function resolveSortColumn(
        ?string $sortBy
    ): string {
        if (
            $sortBy === null
            || ! in_array(
                $sortBy,
                self::SORTABLE_COLUMNS,
                true
            )
        ) {
            return 'id';
        }

        return $sortBy;
    }

    /**
     * Return pagination in both supported response formats.
     */
    private function paginatedResponse(
        $paginator,
        string $message
    ): JsonResponse {
        $meta = [
            'current_page' =>
                $paginator->currentPage(),

            'last_page' =>
                $paginator->lastPage(),

            'per_page' =>
                $paginator->perPage(),

            'total' =>
                $paginator->total(),

            'from' =>
                $paginator->firstItem(),

            'to' =>
                $paginator->lastItem(),
        ];

        return response()->json([
            'success' => true,
            'message' => $message,

            'data' => ItemResource::collection(
                $paginator->items()
            ),

            /*
             * CrudPage expects meta.
             */
            'meta' => $meta,

            /*
             * The Bank implementation currently returns
             * pagination. Keep this for compatibility.
             */
            'pagination' => $meta,
        ]);
    }
}