<?php

namespace App\Http\Requests\Admin;

use Illuminate\Foundation\Http\FormRequest;
use Illuminate\Validation\Rule;

class BankRequest extends FormRequest
{
    public function authorize(): bool
    {
        return true;
    }

    public function rules(): array
    {
        return [
            // Generated by the backend. It is never accepted from the form.
            'bank_id' => ['prohibited'],

            'bank_name' => [
                'required',
                'string',
                'max:100',
            ],

            'bank_name_orginal' => [
                'nullable',
                'string',
                'max:200',
            ],

            'account_no' => [
                'required',
                'string',
                'max:50',
            ],

            'branch' => [
                'required',
                'string',
                'max:50',
            ],

            'contact_address' => [
                'nullable',
                'string',
                'max:50',
            ],

            'begnning_amount' => [
                'required',
                'numeric',
                'min:0',
            ],

            'begnning__amount_left' => [
                'required',
                'numeric',
                'min:0',
            ],

            'min_amount' => [
                'required',
                'numeric',
                'min:0',
            ],

            'transfer_rate' => [
                'required',
                'numeric',
                'min:0',
            ],

            'od_available' => [
                'required',
                Rule::in(['Yes', 'No']),
            ],

            'od_amount' => [
                'nullable',
                'required_if:od_available,Yes',
                'numeric',
                'min:0',
            ],

            'od_amount_left' => [
                'nullable',
                'required_if:od_available,Yes',
                'numeric',
                'min:0',
            ],

            'od_limit' => [
                'nullable',
                'required_if:od_available,Yes',
                'string',
                'max:20',
            ],

            'od_status' => [
                'nullable',
                'required_if:od_available,Yes',
                'string',
                'max:30',
            ],

            'start_date' => [
                'nullable',
                'required_if:od_available,Yes',
                'date_format:Y-m-d',
            ],

            'end_date' => [
                'nullable',
                'required_if:od_available,Yes',
                'date_format:Y-m-d',
                'after_or_equal:start_date',
            ],

            'term_loan' => [
                'required',
                Rule::in(['Yes', 'No']),
            ],

            'term_loan_amount' => [
                'nullable',
                'required_if:term_loan,Yes',
                'numeric',
                'min:0',
            ],

            'loan_status' => [
                'nullable',
                'required_if:term_loan,Yes',
                'string',
                'max:20',
            ],

            'term_loan_start_date' => [
                'nullable',
                'required_if:term_loan,Yes',
                'date_format:Y-m-d',
            ],

            'term_loan_end_date' => [
                'nullable',
                'required_if:term_loan,Yes',
                'date_format:Y-m-d',
                'after_or_equal:term_loan_start_date',
            ],

            'repayment_amount' => [
                'nullable',
                'required_if:term_loan,Yes',
                'numeric',
                'min:0',
            ],

            'repayment_amount_left' => [
                'nullable',
                'required_if:term_loan,Yes',
                'string',
                'max:20',
            ],

            'period' => [
                'nullable',
                'required_if:term_loan,Yes',
                'string',
                'max:20',
            ],

            'term_loan_relief' => [
                'required',
                Rule::in(['Yes', 'No']),
            ],

            'term_loan_relief_start_date' => [
                'nullable',
                'required_if:term_loan_relief,Yes',
                'date_format:Y-m-d',
            ],

            'term_loan_relief_end_date' => [
                'nullable',
                'required_if:term_loan_relief,Yes',
                'date_format:Y-m-d',
                'after_or_equal:term_loan_relief_start_date',
            ],

            'ethiopian_date' => [
                'nullable',
                'string',
                'max:10',
            ],

            'date_registered' => [
                'nullable',
                'date_format:Y-m-d',
            ],

            'cob_balance' => [
                'nullable',
                'string',
                'max:20',
            ],

            'status' => [
                'required',
                Rule::in(['active', 'inactive']),
            ],

            'last_activity' => [
                'nullable',
                'string',
                'max:100',
            ],

            'suggestion' => [
                'nullable',
                'string',
                'max:20',
            ],

            'end_balance' => [
                'nullable',
                'string',
                'max:20',
            ],

            'credit_suggestion' => [
                'nullable',
                'string',
                'max:20',
            ],

            'category' => [
                'nullable',
                'string',
                'max:500',
            ],

            'start_month' => [
                'nullable',
                'string',
                'max:50',
            ],
        ];
    }

    public function messages(): array
    {
        return [
            'bank_id.prohibited' =>
                'Bank ID is generated automatically.',

            'bank_name.required' =>
                'Bank name is required.',

            'account_no.required' =>
                'Account number is required.',

            'branch.required' =>
                'Branch is required.',

            'begnning_amount.required' =>
                'Beginning amount is required.',

            'begnning__amount_left.required' =>
                'Beginning amount left is required.',

            'min_amount.required' =>
                'Minimum amount is required.',

            'transfer_rate.required' =>
                'Transfer rate is required.',

            'od_available.required' =>
                'OD availability is required.',

            'term_loan.required' =>
                'Term loan selection is required.',

            'term_loan_relief.required' =>
                'Term loan relief selection is required.',
        ];
    }
}